export const PUBLIC_ADMIN_BASE_PATH = '/YOMAMA'
export const PUBLIC_ADMIN_LOGIN_PATH = `${PUBLIC_ADMIN_BASE_PATH}/login`
export const PUBLIC_ADMIN_DASHBOARD_PATH = `${PUBLIC_ADMIN_BASE_PATH}/journal`
export const PUBLIC_ADMIN_NEW_POST_PATH = `${PUBLIC_ADMIN_DASHBOARD_PATH}/new`
export const PUBLIC_ADMIN_SETTINGS_PATH = `${PUBLIC_ADMIN_BASE_PATH}/settings`

